---
title: "Untitled"
output: html_document
---
```{r setup, include=FALSE}
library(here)
```
Example 1: Spiked Covariance Model
```{r}
d= 500
K =3
set.seed(151)
u <- matrix(rnorm(d*K), d,K)
u <- svd(u)$u
vi_ls <- c()
runtime <- c()
qr <- qchisq(0.95, df=3)
tab_recov_prob_500 <- c()
err_rate_tab_500 <- c()
runtime_tab_500 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  rec_tab <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("Spiked_Cov_Results","results__500"), i, 6,rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[1,] - H%*%u[1,]
    cv <- sc^2 * t(dv)%*%solve(Sig_hat)%*%dv <= qr
    rec_tab <- c(rec_tab,cv)
    err <- norm(vtild%*%t(vtild) - u%*%t(u),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_500<-rbind(err_rate_tab_500,c(mean(err_rate),rt, d))
  tab_recov_prob_500 <- rbind(tab_recov_prob_500,c(mean(rec_tab),rt, d))
  runtime_tab_500<-rbind(runtime_tab_500,c(mean(runtime_ls),rt, d))
}

###traditional PCA
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_1_n/pca/results/results__500", i, ".RData",sep = "_")
  load(fname)
  err <- norm(vkh%*%t(vkh) - u%*%t(u),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
}
er_pca_500 <- mean(err_rate)
runtime_pca_500 <- mean(runtime_ls)

d= 1000
K =3
set.seed(151)
u <- matrix(rnorm(d*K), d,K)
u <- svd(u)$u
vi_ls <- c()
runtime <- c()
qr <- qchisq(0.95, df=3)
tab_recov_prob_1000 <- c()
err_rate_tab_1000 <- c()
runtime_tab_1000 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  rec_tab <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("Spiked_Cov_Results","results__1000"), i, 6,rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[1,] - H%*%u[1,]
    cv <- sc^2 * t(dv)%*%solve(Sig_hat)%*%dv <= qr
    rec_tab <- c(rec_tab,cv)
    err <- norm(vtild%*%t(vtild) - u%*%t(u),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
  }
  err_rate_tab_1000<-rbind(err_rate_tab_1000,c(mean(err_rate),rt, d))
  tab_recov_prob_1000 <- rbind(tab_recov_prob_1000,c(mean(rec_tab),rt, d))
  runtime_tab_1000<-rbind(runtime_tab_1000,c(mean(runtime_ls),rt, d))
}

###traditional PCA
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_1_n/pca/results/results__1000", i, ".RData",sep = "_")
  load(fname)
  err <- norm(vkh%*%t(vkh) - u%*%t(u),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
}
er_pca_1000 <- mean(err_rate)
runtime_pca_1000 <- mean(runtime_ls)

d= 2000
K =3
set.seed(151)
u <- matrix(rnorm(d*K), d,K)
u <- svd(u)$u
vi_ls <- c()
runtime <- c()
qr <- qchisq(0.95, df=3)
tab_recov_prob_2000 <- c()
err_rate_tab_2000 <- c()
runtime_tab_2000 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  rec_tab <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("Spiked_Cov_Results","results__2000"), i, 6,rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[1,] - H%*%u[1,]
    cv <- sc^2 * t(dv)%*%solve(Sig_hat)%*%dv <= qr
    rec_tab <- c(rec_tab,cv)
    err <- norm(vtild%*%t(vtild) - u%*%t(u),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_2000<-rbind(err_rate_tab_2000,c(mean(err_rate),rt, d))
  tab_recov_prob_2000 <- rbind(tab_recov_prob_2000,c(mean(rec_tab),rt, d))
  runtime_tab_2000<-rbind(runtime_tab_2000,c(mean(runtime_ls),rt, d))
}

###traditional PCA
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_1_n/pca/results/results__2000", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - u%*%t(u),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_2000 <- mean(err_rate)
runtime_pca_2000 <- mean(runtime_ls)


#### tables for plotting
err_rate_tab <- rbind(err_rate_tab_500,err_rate_tab_1000, err_rate_tab_2000)
err_rate_tab <- data.frame(err_rate_tab)
err_rate_tab$X3<- as.factor(err_rate_tab$X3 )
tab_recov_prob <- rbind(tab_recov_prob_500, tab_recov_prob_1000, tab_recov_prob_2000)
runtime_tab <- rbind(runtime_tab_500, runtime_tab_1000, runtime_tab_2000)
runtime_tab <- data.frame(runtime_tab)
runtime_tab$X3<- as.factor(runtime_tab$X3 )
tab_recov_prob <- data.frame(tab_recov_prob)
tab_recov_prob$X3<- as.factor(tab_recov_prob$X3 )

#### Plots in Figure 2
library(RColorBrewer)
library(latex2exp)
p<-ggplot(mapping = aes(x=tab_recov_prob[,2],y=(tab_recov_prob[,1]),group =tab_recov_prob[,3] ))+geom_point(aes(color = tab_recov_prob[,3], shape = tab_recov_prob[,3]), size = 2.5 )+ geom_hline(yintercept = 0.95, color = "grey", linetype =2)  + geom_line(aes(color = tab_recov_prob[,3], linetype = tab_recov_prob[,3]) , size = 0.7)+labs(x=TeX("$Lp/d$"), y = "Empirical Coverage Probability",color = TeX("$d$"), shape =  TeX("$d$"), linetype =  TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) +scale_color_brewer(palette = "Set2")
p1<-ggplot(mapping = aes(x=err_rate_tab[,2],y=(err_rate_tab[,1]),group =err_rate_tab[,3] ))+geom_point(aes(color = err_rate_tab[,3], shape = err_rate_tab[,3]) , size = 2.5) + geom_hline(yintercept = er_pca_500, color = "grey", linetype =2) +  geom_hline(yintercept = er_pca_1000, color = "grey", linetype =2)  +  geom_hline(yintercept = er_pca_2000, color = "grey", linetype =2)   + geom_line(aes(color = err_rate_tab[,3], linetype = err_rate_tab[,3]) , size = 0.7)+labs(x=TeX("$Lp/d$"), y = "Error Rate",color = TeX("$d$"), shape = TeX("$d$"), linetype = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) +scale_color_brewer(palette = "Set2")
p2<-ggplot(mapping = aes(x=runtime_tab[,2],y=(runtime_tab[,1]),group =runtime_tab[,3] ))+geom_point(aes(color = runtime_tab[,3], shape = runtime_tab[,3]) , size = 2.5)  + geom_line(aes(color = runtime_tab[,3], linetype = runtime_tab[,3]), size = 0.7 )+labs(x=TeX("$Lp/d$"), y = "Running Time",color = TeX("$d$"), shape = TeX("$d$"), linetype = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) +scale_color_brewer(palette = "Set2")

##### QQ plot in Figure 2
d= 500
K =3
set.seed(151)
u <- matrix(rnorm(d*K), d,K)
u <- svd(u)$u


vi_ls <- c()


for (rt in c(0.2,10)){
  for (i in 1:300){
    fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_1/results1/results__500", i, 6,rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[1,] - H%*%u[1,]
    
    svdsig <- svd(Sig_hat)
    sig_sqrt <- svdsig$u %*% diag((svdsig$d)^{-0.5}) %*% t(svdsig$u)
    vi <- vtild[1,] - H%*% u[1,]
    vi_ls <- rbind(vi_ls,c(t(sig_sqrt%*%(vi*sc)),rt))
    
    
  }
  
}
vi_ls <- data.frame(vi_ls)
vi_ls[4] <- factor(vi_ls[,4])
p1 <- ggplot()+geom_qq(aes(sample = vi_ls[,1],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{v}_{1,1}$"), color = TeX("$Lp/d$"))
p2 <- ggplot()+geom_qq(aes(sample = vi_ls[,2],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{v}_{2,1}$"), color = TeX("$Lp/d$"))
p3 <- ggplot()+geom_qq(aes(sample = vi_ls[,3],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{v}_{3,1}$"), color = TeX("$Lp/d$"))
```



Example 2: GMM
```{r}
d=500
K = 3
n = 20000
Delta2 = n^{2/3}
p = 4*K
p0 = 4*K
set.seed(152)
Theta = matrix(rnorm(n*K), n, K)
Theta <- Theta * (Delta2/2/n)^{0.5}


F_st <- matrix(0,d,K)
nk <- round(d/K)


for (k in 1:(K-1)){
  F_st[(((k-1)*nk+1):(k*nk)),k] <- 1
}
F_st[(((K-1)*nk+1):d),K] <- 1

svd1 <- svd(F_st)

mid <- t(Theta) %*% Theta
svd2 <- svd(mid)

u <- svd1$u %*% svd2$u




vi_ls <- c()
runtime <- c()

qr <- qchisq(0.95, df=3)
tab_recov_prob_500 <- c()
err_rate_tab_500 <- c()
runtime_tab_500 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  rec_tab <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("GMM_Results","results__500"), i, rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[1,] - H%*%u[1,]
    cv <- sc^2 * t(dv)%*%solve(Sig_hat)%*%dv <= qr
    
    
    
    rec_tab <- c(rec_tab,cv)
    
    err <- norm(vtild%*%t(vtild) - u%*%t(u),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_500<-rbind(err_rate_tab_500,c(mean(err_rate),rt, d))
  tab_recov_prob_500 <- rbind(tab_recov_prob_500,c(mean(rec_tab),rt, d))
  runtime_tab_500<-rbind(runtime_tab_500,c(mean(runtime_ls),rt, d))
}


###traditional PCA
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_3_n/pca/results/results__500", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - u%*%t(u),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_500 <- mean(err_rate)
runtime_pca_500 <- mean(runtime_ls)

d = 1000

set.seed(152)
Theta = matrix(rnorm(n*K), n, K)
Theta <- Theta * (Delta2/2/n)^{0.5}


F_st <- matrix(0,d,K)
nk <- round(d/K)


for (k in 1:(K-1)){
  F_st[(((k-1)*nk+1):(k*nk)),k] <- 1
}
F_st[(((K-1)*nk+1):d),K] <- 1

svd1 <- svd(F_st)

mid <- t(Theta) %*% Theta
svd2 <- svd(mid)

u <- svd1$u %*% svd2$u


vi_ls <- c()
runtime <- c()

qr <- qchisq(0.95, df=3)
tab_recov_prob_1000 <- c()
err_rate_tab_1000 <- c()
runtime_tab_1000 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  rec_tab <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("GMM_Results","results__1000"), i,rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[1,] - H%*%u[1,]
    cv <- sc^2 * t(dv)%*%solve(Sig_hat)%*%dv <= qr
    
    
    
    rec_tab <- c(rec_tab,cv)
    
    err <- norm(vtild%*%t(vtild) - u%*%t(u),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_1000<-rbind(err_rate_tab_1000,c(mean(err_rate),rt, d))
  tab_recov_prob_1000 <- rbind(tab_recov_prob_1000,c(mean(rec_tab),rt, d))
  runtime_tab_1000<-rbind(runtime_tab_1000,c(mean(runtime_ls),rt, d))
}

###traditional PCA
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_3_n/pca/results/results__1000", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - u%*%t(u),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_1000 <- mean(err_rate)
runtime_pca_1000 <- mean(runtime_ls)

d = 2000

set.seed(152)
Theta = matrix(rnorm(n*K), n, K)
Theta <- Theta * (Delta2/2/n)^{0.5}


F_st <- matrix(0,d,K)
nk <- round(d/K)


for (k in 1:(K-1)){
  F_st[(((k-1)*nk+1):(k*nk)),k] <- 1
}
F_st[(((K-1)*nk+1):d),K] <- 1

svd1 <- svd(F_st)

mid <- t(Theta) %*% Theta
svd2 <- svd(mid)

u <- svd1$u %*% svd2$u



vi_ls <- c()
runtime <- c()

qr <- qchisq(0.95, df=3)
tab_recov_prob_2000 <- c()
err_rate_tab_2000 <- c()
runtime_tab_2000 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  rec_tab <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("GMM_Results","results__2000"), i, rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[1,] - H%*%u[1,]
    cv <- sc^2 * t(dv)%*%solve(Sig_hat)%*%dv <= qr
    
    
    
    rec_tab <- c(rec_tab,cv)
    
    err <- norm(vtild%*%t(vtild) - u%*%t(u),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_2000<-rbind(err_rate_tab_2000,c(mean(err_rate),rt, d))
  tab_recov_prob_2000 <- rbind(tab_recov_prob_2000,c(mean(rec_tab),rt, d))
  runtime_tab_2000<-rbind(runtime_tab_2000,c(mean(runtime_ls),rt, d))
}


###traditional PCA
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_3_n/pca/results/results__2000", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - u%*%t(u),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_2000 <- mean(err_rate)
runtime_pca_2000 <- mean(runtime_ls)


###### Tables for producing Figure 3

err_rate_tab <- rbind(err_rate_tab_500,err_rate_tab_1000, err_rate_tab_2000)
err_rate_tab <- data.frame(err_rate_tab)
err_rate_tab$X3<- as.factor(err_rate_tab$X3 )


tab_recov_prob <- rbind(tab_recov_prob_500, tab_recov_prob_1000, tab_recov_prob_2000)

runtime_tab <- rbind(runtime_tab_500, runtime_tab_1000, runtime_tab_2000)
runtime_tab <- data.frame(runtime_tab)
runtime_tab$X3<- as.factor(runtime_tab$X3 )

tab_recov_prob <- data.frame(tab_recov_prob)
tab_recov_prob$X3<- as.factor(tab_recov_prob$X3 )

#### Plotting Figure 3
library(latex2exp)
p<-ggplot(mapping = aes(x=tab_recov_prob[,2],y=(tab_recov_prob[,1]),group =tab_recov_prob[,3]))+geom_point(aes(color = tab_recov_prob[,3], shape = tab_recov_prob[,3]) )+  geom_hline(yintercept = 0.95, color = "grey", linetype =2)  + geom_line(aes(color = tab_recov_prob[,3], linetype = tab_recov_prob[,3]) )+labs(x=TeX("$Lp/d$"), y = "Empirical Coverage Probability",color = TeX("$d$"),shape = TeX("$d$"), linetype = TeX("$d$") )+theme_bw()+theme(text=element_text(family="Times", size=12))  + scale_color_viridis(discrete = TRUE)
p1<-ggplot(mapping = aes(x=err_rate_tab[,2],y=(err_rate_tab[,1]),group =err_rate_tab[,3] ))+geom_point(aes(color = err_rate_tab[,3], shape = err_rate_tab[,3]) )+ geom_hline(yintercept = er_pca_500, color = "grey", linetype =2) +  geom_hline(yintercept = er_pca_1000, color = "grey", linetype =2)  +  geom_hline(yintercept = er_pca_2000, color = "grey", linetype =2)   + geom_line(aes(color = err_rate_tab[,3],linetype = err_rate_tab[,3]) )+labs(x=TeX("$Lp/d$"), y = "Error Rate",color = TeX("$d$"),shape = TeX("$d$"), linetype = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) + scale_color_viridis(discrete = TRUE)
p2<-ggplot(mapping = aes(x=runtime_tab[,2],y=(runtime_tab[,1]),group =runtime_tab[,3] ))+geom_point(aes(color = runtime_tab[,3], shape = runtime_tab[,3]) )  + geom_line(aes(color = runtime_tab[,3], linetype = runtime_tab[,3]) )+labs(x=TeX("$Lp/d$"), y = "Running Time",color = TeX("$d$"),shape = TeX("$d$"), linetype = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) + scale_color_viridis(discrete = TRUE)

p3<-ggplot(mapping = aes(x=mis_cluster_rt_mat[,2],y=(mis_cluster_rt_mat[,1]),group =mis_cluster_rt_mat[,3] ))+geom_point(aes(color = mis_cluster_rt_mat[,3], shape = mis_cluster_rt_mat[,3]) )+ geom_hline(yintercept = mis_rt_pca_ls[1,2], color = "grey", linetype =2) +  geom_hline(yintercept = mis_rt_pca_ls[2,2], color = "grey", linetype =2)  +  geom_hline(yintercept = mis_rt_pca_ls[3,2], color = "grey", linetype =2)   + geom_line(aes(color = mis_cluster_rt_mat[,3],linetype = mis_cluster_rt_mat[,3]) )+labs(x=TeX("$Lp/d$"), y = "Misclustering Rate",color = TeX("$d$"),shape = TeX("$d$"), linetype = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) + scale_color_viridis(discrete = TRUE)
```
```{r}
##### QQ plots in Figure 3
d=500
K = 3
n = 20000
Delta2 = n^{2/3}
p = 4*K
p0 = 4*K
set.seed(152)
Theta = matrix(rnorm(n*K), n, K)
Theta <- Theta * (Delta2/2/n)^{0.5}


F_st <- matrix(0,d,K)
nk <- round(d/K)


for (k in 1:(K-1)){
  F_st[(((k-1)*nk+1):(k*nk)),k] <- 1
}
F_st[(((K-1)*nk+1):d),K] <- 1

svd1 <- svd(F_st)

mid <- t(Theta) %*% Theta
svd2 <- svd(mid)

u <- svd1$u %*% svd2$u



vi_ls <- c()


for (rt in c(0.2,10)){
  for (i in 1:300){
    fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_3/results1/results__500", i, rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[1,] - H%*%u[1,]
    
    svdsig <- svd(Sig_hat)
    sig_sqrt <- svdsig$u %*% diag((svdsig$d)^{-0.5}) %*% t(svdsig$u)
    vi <- vtild[1,] - H%*% u[1,]
    vi_ls <- rbind(vi_ls,c(t(sig_sqrt%*%(vi*sc)),rt))
    
    
  }
  
}
vi_ls <- data.frame(vi_ls)
vi_ls[4] <- factor(vi_ls[,4])
p1 <- ggplot()+geom_qq(aes(sample = vi_ls[,1],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{v}_{1,1}$"), color = TeX("$Lp/d$"))
p2 <- ggplot()+geom_qq(aes(sample = vi_ls[,2],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{v}_{2,1}$"), color = TeX("$Lp/d$"))
p3 <- ggplot()+geom_qq(aes(sample = vi_ls[,3],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{v}_{3,1}$"), color = TeX("$Lp/d$"))
```


Example 3: DCMM
```{r}
d=500

K =3
a = 0.7
b = 0.2


p = 4*K
p0 = 4*K
rt = 10
L = round(rt*d/p)
lmode = 1
q = 7
it = 1



ext = 12

set.seed(153)
piset1 <- diag(rep(1,3))
piset2 <- rbind(c(0.6,0.2,0.2),c(0.2,0.6,0.2),c(0.2,0.2,0.6),rep(1,3)/3)



Pi1 <- matrix(0,d/2,K)
nk <- round(d/K/2)
for (k in 1:(K-1)){
  Pi1[(((k-1)*nk+1):(k*nk)),] <- rep(piset1[k,],each = nk)
  
}
Pi1[(((K-1)*nk+1):(d/2)),] <- rep(piset1[K,],each = d/2-2*nk)

Pi2 <- matrix(0,d/2,K)
nk <- round(d/8)
for (k in 1:(4-1)){
  Pi2[(((k-1)*nk+1):(k*nk)),] <- rep(piset2[k,],each = nk)
  
}
Pi2[(((4-1)*nk+1):(d/2)),] <- rep(piset2[4,],each = d/2-3*nk)

Pi1 <- rbind(Pi1,Pi2)
P <- matrix(c(1,0.2,0.1,0.2,1,0.2,0.1,0.2,1),3,3)
svd1 <- svd(Pi1)

mid <- diag(svd1$d) %*% t(svd1$v) %*% P %*% svd1$v %*% diag(svd1$d)
svd2 <- svd(mid)

Vk <- svd1$u %*% svd2$u


vi_ls <- c()
runtime <- c()

qr <- qchisq(0.95, df=3)
tab_recov_prob1_500 <- c()

tab_recov_prob_500 <- c()
err_rate_tab_500 <- c()
runtime_tab_500 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  rec_tab <- c()
  rec_tab1 <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("DCMM_Results","results__500"), i,rt, ".RData",sep = "_")
    load(fname)
    
    i = 3
    j = 6
    dv <- vtild[d/2+i,] - vtild[d/2+j,]
    if (rt >= 1){
      Sig_hat01 <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d/2+i,])*(1-Mtild[d/2+i,])   ) *vtild  )%*%solve(lmtild)
      Sig_hat02 <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d/2+j,])*(1-Mtild[d/2+j,])   ) *vtild  )%*%solve(lmtild)}else{
        Sig_hat01 <- t(Bo)%*%t(Omega)%*%( (   (Mtild[d/2+i,])*(1-Mtild[d/2+i,])   ) *Omega  )%*%Bo/L^2
        Sig_hat02 <- t(Bo)%*%t(Omega)%*%( (   (Mtild[d/2+j,])*(1-Mtild[d/2+j,])   ) *Omega  )%*%Bo/L^2
      }
    cv <-  t(dv)%*%solve(Sig_hat01+Sig_hat02)%*%dv <= qr
    
    dv1 <- vtild[d/2+i,] - vtild[d,]
    if (rt >= 1){
      Sig_hatd <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d,])*(1-Mtild[d,])   ) *vtild  )%*%solve(lmtild)}else{
        Sig_hatd <- t(Bo)%*%t(Omega)%*%( (   (Mtild[d,])*(1-Mtild[d,])   ) *Omega  )%*%Bo/L^2
      }
    
    
    Sig_hat_1 <- Sig_hat01 + Sig_hatd
    cv1 <-  t(dv1)%*%solve(Sig_hat_1)%*%dv1 > qr
    
    
    rec_tab <- c(rec_tab,cv)
    rec_tab1 <- c(rec_tab1,cv1)
    
    err <- norm(vtild%*%t(vtild) - Vk%*%t(Vk),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_500<-rbind(err_rate_tab_500,c(mean(err_rate),rt, d))
  tab_recov_prob_500 <- rbind(tab_recov_prob_500,c(mean(rec_tab),rt, d))
  tab_recov_prob1_500 <- rbind(tab_recov_prob1_500,c(mean(rec_tab1),rt, d))
  runtime_tab_500<-rbind(runtime_tab_500,c(mean(runtime_ls),rt, d))
}




d=1000

K =3
a = 0.7
b = 0.2


p = 4*K
p0 = 4*K
rt = 10
L = round(rt*d/p)
lmode = 1
q = 7
it = 1



ext = 12

set.seed(153)
piset1 <- diag(rep(1,3))
piset2 <- rbind(c(0.6,0.2,0.2),c(0.2,0.6,0.2),c(0.2,0.2,0.6),rep(1,3)/3)

Pi1 <- matrix(0,d/2,K)
nk <- round(d/K/2)
for (k in 1:(K-1)){
  Pi1[(((k-1)*nk+1):(k*nk)),] <- rep(piset1[k,],each = nk)
  
}
Pi1[(((K-1)*nk+1):(d/2)),] <- rep(piset1[K,],each = d/2-2*nk)

Pi2 <- matrix(0,d/2,K)
nk <- round(d/8)
for (k in 1:(4-1)){
  Pi2[(((k-1)*nk+1):(k*nk)),] <- rep(piset2[k,],each = nk)
  
}
Pi2[(((4-1)*nk+1):(d/2)),] <- rep(piset2[4,],each = d/2-3*nk)

Pi1 <- rbind(Pi1,Pi2)
P <- matrix(c(1,0.2,0.1,0.2,1,0.2,0.1,0.2,1),3,3)

svd1 <- svd(Pi1)

mid <- diag(svd1$d) %*% t(svd1$v) %*% P %*% svd1$v %*% diag(svd1$d)
svd2 <- svd(mid)

Vk <- svd1$u %*% svd2$u


vi_ls <- c()
runtime <- c()

qr <- qchisq(0.95, df=3)
tab_recov_prob_1000 <- c()
tab_recov_prob1_1000 <- c()
err_rate_tab_1000 <- c()
runtime_tab_1000 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  rec_tab <- c()
  rec_tab1 <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("DCMM_Results","results__1000"), i,rt, ".RData",sep = "_")
    load(fname)
    
    i = 3
    j = 9 
    dv <- vtild[d/2+i,] - vtild[d/2+j,]
    if (rt >= 1){
      Sig_hat01 <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d/2+i,])*(1-Mtild[d/2+i,])   ) *vtild  )%*%solve(lmtild)
      Sig_hat02 <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d/2+j,])*(1-Mtild[d/2+j,])   ) *vtild  )%*%solve(lmtild)}else{
        Sig_hat01 <- t(Bo)%*%t(Omega)%*%( (   (Mtild[d/2+i,])*(1-Mtild[d/2+i,])   ) *Omega  )%*%Bo/L^2
        Sig_hat02 <- t(Bo)%*%t(Omega)%*%( (   (Mtild[d/2+j,])*(1-Mtild[d/2+j,])   ) *Omega  )%*%Bo/L^2
      }
    cv <-  t(dv)%*%solve(Sig_hat01+Sig_hat02)%*%dv <= qr
    
    dv1 <- vtild[d/2+i,] - vtild[d,]
    if (rt >= 1){
      Sig_hatd <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d,])*(1-Mtild[d,])   ) *vtild  )%*%solve(lmtild)}else{
        Sig_hatd <- t(Bo)%*%t(Omega)%*%( (   (Mtild[d,])*(1-Mtild[d,])   ) *Omega  )%*%Bo/L^2
      }
    
    
    Sig_hat_1 <- Sig_hat01 + Sig_hatd
    cv1 <-  t(dv1)%*%solve(Sig_hat_1)%*%dv1 > qr
    
    rec_tab <- c(rec_tab,cv)
    rec_tab1 <- c(rec_tab1,cv1)
    
    err <- norm(vtild%*%t(vtild) - Vk%*%t(Vk),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_1000<-rbind(err_rate_tab_1000,c(mean(err_rate),rt, d))
  tab_recov_prob_1000 <- rbind(tab_recov_prob_1000,c(mean(rec_tab),rt, d))
  tab_recov_prob1_1000 <- rbind(tab_recov_prob1_1000,c(mean(rec_tab1),rt, d))
  runtime_tab_1000<-rbind(runtime_tab_1000,c(mean(runtime_ls),rt, d))
}




d=2000

K =3
a = 0.7
b = 0.2


p = 4*K
p0 = 4*K
rt = 10
L = round(rt*d/p)
lmode = 1
q = 7
it = 1



ext = 12

set.seed(153)
piset1 <- diag(rep(1,3))
piset2 <- rbind(c(0.6,0.2,0.2),c(0.2,0.6,0.2),c(0.2,0.2,0.6),rep(1,3)/3)

Pi1 <- matrix(0,d/2,K)
nk <- round(d/K/2)
for (k in 1:(K-1)){
  Pi1[(((k-1)*nk+1):(k*nk)),] <- rep(piset1[k,],each = nk)
  
}
Pi1[(((K-1)*nk+1):(d/2)),] <- rep(piset1[K,],each = d/2-2*nk)

Pi2 <- matrix(0,d/2,K)
nk <- round(d/8)
for (k in 1:(4-1)){
  Pi2[(((k-1)*nk+1):(k*nk)),] <- rep(piset2[k,],each = nk)
  
}
Pi2[(((4-1)*nk+1):(d/2)),] <- rep(piset2[4,],each = d/2-3*nk)

Pi1 <- rbind(Pi1,Pi2)
P <- matrix(c(1,0.2,0.1,0.2,1,0.2,0.1,0.2,1),3,3)
svd1 <- svd(Pi1)

mid <- diag(svd1$d) %*% t(svd1$v) %*% P %*% svd1$v %*% diag(svd1$d)
svd2 <- svd(mid)

Vk <- svd1$u %*% svd2$u


vi_ls <- c()
runtime <- c()

qr <- qchisq(0.95, df=3)
tab_recov_prob_2000 <- c()
tab_recov_prob1_2000 <- c()
err_rate_tab_2000 <- c()
runtime_tab_2000 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  rec_tab <- c()
  rec_tab1 <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("DCMM_Results","results__2000"), i,rt, ".RData",sep = "_")
    load(fname)
    i = 9
    j = 10 
    dv <- vtild[d/2+i,] - vtild[d/2+j,]
    if (rt >= 1){
      Sig_hat01 <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d/2+i,])*(1-Mtild[d/2+i,])   ) *vtild  )%*%solve(lmtild)
      Sig_hat02 <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d/2+j,])*(1-Mtild[d/2+j,])   ) *vtild  )%*%solve(lmtild)}else{
        Sig_hat01 <- t(Bo)%*%t(Omega)%*%( (   (Mtild[d/2+i,])*(1-Mtild[d/2+i,])   ) *Omega  )%*%Bo/L^2
        Sig_hat02 <- t(Bo)%*%t(Omega)%*%( (   (Mtild[d/2+j,])*(1-Mtild[d/2+j,])   ) *Omega  )%*%Bo/L^2
      }
    cv <-  t(dv)%*%solve(Sig_hat01+Sig_hat02)%*%dv <= qr
    
    dv1 <- vtild[d/2+i,] - vtild[d,]
    if (rt >= 1){
      Sig_hatd <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d,])*(1-Mtild[d,])   ) *vtild  )%*%solve(lmtild)}else{
        Sig_hatd <- t(Bo)%*%t(Omega)%*%( (   (Mtild[d,])*(1-Mtild[d,])   ) *Omega  )%*%Bo/L^2
      }
    
    
    Sig_hat_1 <- Sig_hat01 + Sig_hatd
    cv1 <-  t(dv1)%*%solve(Sig_hat_1)%*%dv1 > qr
    
    
    rec_tab <- c(rec_tab,cv)
    rec_tab1 <- c(rec_tab1,cv1)
    
    err <- norm(vtild%*%t(vtild) - Vk%*%t(Vk),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_2000<-rbind(err_rate_tab_2000,c(mean(err_rate),rt, d))
  tab_recov_prob_2000 <- rbind(tab_recov_prob_2000,c(mean(rec_tab),rt, d))
  tab_recov_prob1_2000 <- rbind(tab_recov_prob1_2000,c(mean(rec_tab1),rt, d))
  
  runtime_tab_2000<-rbind(runtime_tab_2000,c(mean(runtime_ls),rt, d))
}




##### tables for plotting Figure 5

err_rate_tab <- rbind(err_rate_tab_500,err_rate_tab_1000, err_rate_tab_2000)
err_rate_tab <- data.frame(err_rate_tab)
err_rate_tab$X3<- as.factor(err_rate_tab$X3 )



runtime_tab <- rbind(runtime_tab_500, runtime_tab_1000, runtime_tab_2000)
runtime_tab <- data.frame(runtime_tab)
runtime_tab$X3<- as.factor(runtime_tab$X3 )

tab_recov_prob <- rbind(tab_recov_prob_500, tab_recov_prob_1000, tab_recov_prob_2000)
tab_recov_prob <- data.frame(tab_recov_prob)
tab_recov_prob$X3<- as.factor(tab_recov_prob$X3 )

tab_recov_prob1 <- rbind(tab_recov_prob1_500, tab_recov_prob1_1000, tab_recov_prob1_2000)
tab_recov_prob1 <- data.frame(tab_recov_prob1)
tab_recov_prob1$X3<- as.factor(tab_recov_prob1$X3 )

####### QQ plot in Figure 5

d=2000

K =3
a = 0.7
b = 0.2


p = 4*K
p0 = 4*K
rt = 10
L = round(rt*d/p)
lmode = 1
q = 7
it = 1



ext = 12

set.seed(153)
piset1 <- diag(rep(1,3))
piset2 <- rbind(c(0.6,0.2,0.2),c(0.2,0.6,0.2),c(0.2,0.2,0.6),rep(1,3)/3)



Pi1 <- matrix(0,d/2,K)
nk <- round(d/K/2)
for (k in 1:(K-1)){
  Pi1[(((k-1)*nk+1):(k*nk)),] <- rep(piset1[k,],each = nk)
  
}
Pi1[(((K-1)*nk+1):(d/2)),] <- rep(piset1[K,],each = d/2-2*nk)

Pi2 <- matrix(0,d/2,K)
nk <- round(d/8)
for (k in 1:(4-1)){
  Pi2[(((k-1)*nk+1):(k*nk)),] <- rep(piset2[k,],each = nk)
  
}
Pi2[(((4-1)*nk+1):(d/2)),] <- rep(piset2[4,],each = d/2-3*nk)

Pi1 <- rbind(Pi1,Pi2)
P <- matrix(c(1,0.2,0.1,0.2,1,0.2,0.1,0.2,1),3,3)
svd1 <- svd(Pi1)

mid <- diag(svd1$d) %*% t(svd1$v) %*% P %*% svd1$v %*% diag(svd1$d)
svd2 <- svd(mid)

u <- svd1$u %*% svd2$u


vi_ls <- c()

for(rt in c(0.2,10)){
  for (i in 1:300){
    fname  <- paste(here("DCMM_Results","results__2000"), i, rt, ".RData",sep = "_")
    load(fname)
    #svdh <- svd(t(vtild)%*%u)
    #H <- svdh$u %*% t(svdh$v)
    
    i = 9
    j = 10 
    
    Sig_hat01 <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d/2+i,])*(1-Mtild[d/2+i,])   ) *vtild  )%*%solve(lmtild)
    Sig_hat02 <- solve(lmtild)%*%t(vtild)%*%( (    (Mtild[d/2+j,])*(1-Mtild[d/2+j,])   ) *vtild  )%*%solve(lmtild)
    svdsig <- svd(Sig_hat01 + Sig_hat02)
    sig_sqrt <- svdsig$u %*% diag((svdsig$d)^{-0.5}) %*% t(svdsig$u)
    vi <- vtild[d/2+i,] - vtild[d/2+j,]
    vi_ls <- rbind(vi_ls,c(t(sig_sqrt%*%(vi)),rt))
    
    
  }
  
}
vi_ls <- data.frame(vi_ls)
vi_ls[4] <- factor(vi_ls[,4])
p1 <- ggplot()+geom_qq(aes(sample = vi_ls[,1],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme_bw()+theme(axis.text=element_text(family="Times", size=12),axis.title=element_text(family="Times", size=12),legend.text=element_text(family="Times", size=12))+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{d}_{1}$"), color = TeX("$Lp/d$"))
p2 <- ggplot()+geom_qq(aes(sample = vi_ls[,2],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(family="Times", size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{d}_{2}$"), color = TeX("$Lp/d$"))
p3 <- ggplot()+geom_qq(aes(sample = vi_ls[,3],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(family="Times", size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(family="Times", size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{d}_{3}$"), color = TeX("$Lp/d$"))


```
```{r}
###traditional PCA results for DCMM
d=500

K =3
a = 0.7
b = 0.2


p = 4*K
p0 = 4*K
rt = 10
L = round(rt*d/p)
lmode = 1
q = 7
it = 1



ext = 12

set.seed(153)
piset1 <- diag(rep(1,3))
piset2 <- rbind(c(0.6,0.2,0.2),c(0.2,0.6,0.2),c(0.2,0.2,0.6),rep(1,3)/3)

Pi1 <- matrix(0,d/2,K)
nk <- round(d/K/2)
for (k in 1:(K-1)){
  Pi1[(((k-1)*nk+1):(k*nk)),] <- rep(piset1[k,],each = nk)
  
}
Pi1[(((K-1)*nk+1):(d/2)),] <- rep(piset1[K,],each = d/2-2*nk)

Pi2 <- matrix(0,d/2,K)
nk <- round(d/8)
for (k in 1:(4-1)){
  Pi2[(((k-1)*nk+1):(k*nk)),] <- rep(piset2[k,],each = nk)
  
}
Pi2[(((4-1)*nk+1):(d/2)),] <- rep(piset2[4,],each = d/2-3*nk)

Pi1 <- rbind(Pi1,Pi2)
P <- matrix(c(1,0.2,0.1,0.2,1,0.2,0.1,0.2,1),3,3)
svd1 <- svd(Pi1)

mid <- diag(svd1$d) %*% t(svd1$v) %*% P %*% svd1$v %*% diag(svd1$d)
svd2 <- svd(mid)

Vk <- svd1$u %*% svd2$u
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_2/pca/results/results__500", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - Vk%*%t(Vk),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_500 <- mean(err_rate)
runtime_pca_500 <- mean(runtime_ls)

###traditional PCA
d=1000

K =3
a = 0.7
b = 0.2


p = 4*K
p0 = 4*K
rt = 10
L = round(rt*d/p)
lmode = 1
q = 7
it = 1



ext = 12

set.seed(153)
piset1 <- diag(rep(1,3))
piset2 <- rbind(c(0.6,0.2,0.2),c(0.2,0.6,0.2),c(0.2,0.2,0.6),rep(1,3)/3)

Pi1 <- matrix(0,d/2,K)
nk <- round(d/K/2)
for (k in 1:(K-1)){
  Pi1[(((k-1)*nk+1):(k*nk)),] <- rep(piset1[k,],each = nk)
  
}
Pi1[(((K-1)*nk+1):(d/2)),] <- rep(piset1[K,],each = d/2-2*nk)

Pi2 <- matrix(0,d/2,K)
nk <- round(d/8)
for (k in 1:(4-1)){
  Pi2[(((k-1)*nk+1):(k*nk)),] <- rep(piset2[k,],each = nk)
  
}
Pi2[(((4-1)*nk+1):(d/2)),] <- rep(piset2[4,],each = d/2-3*nk)

Pi1 <- rbind(Pi1,Pi2)
P <- matrix(c(1,0.2,0.1,0.2,1,0.2,0.1,0.2,1),3,3)
svd1 <- svd(Pi1)

mid <- diag(svd1$d) %*% t(svd1$v) %*% P %*% svd1$v %*% diag(svd1$d)
svd2 <- svd(mid)

Vk <- svd1$u %*% svd2$u
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_2/pca/results/results__1000", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - Vk%*%t(Vk),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_1000 <- mean(err_rate)
runtime_pca_1000 <- mean(runtime_ls)

###traditional PCA
d=2000

K =3
a = 0.7
b = 0.2


p = 4*K
p0 = 4*K
rt = 10
L = round(rt*d/p)
lmode = 1
q = 7
it = 1



ext = 12

set.seed(153)
piset1 <- diag(rep(1,3))
piset2 <- rbind(c(0.6,0.2,0.2),c(0.2,0.6,0.2),c(0.2,0.2,0.6),rep(1,3)/3)

Pi1 <- matrix(0,d/2,K)
nk <- round(d/K/2)
for (k in 1:(K-1)){
  Pi1[(((k-1)*nk+1):(k*nk)),] <- rep(piset1[k,],each = nk)
  
}
Pi1[(((K-1)*nk+1):(d/2)),] <- rep(piset1[K,],each = d/2-2*nk)

Pi2 <- matrix(0,d/2,K)
nk <- round(d/8)
for (k in 1:(4-1)){
  Pi2[(((k-1)*nk+1):(k*nk)),] <- rep(piset2[k,],each = nk)
  
}
Pi2[(((4-1)*nk+1):(d/2)),] <- rep(piset2[4,],each = d/2-3*nk)

Pi1 <- rbind(Pi1,Pi2)
P <- matrix(c(1,0.2,0.1,0.2,1,0.2,0.1,0.2,1),3,3)
svd1 <- svd(Pi1)

mid <- diag(svd1$d) %*% t(svd1$v) %*% P %*% svd1$v %*% diag(svd1$d)
svd2 <- svd(mid)

Vk <- svd1$u %*% svd2$u
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_2/pca/results/results__2000", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - Vk%*%t(Vk),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_2000 <- mean(err_rate)
runtime_pca_2000 <- mean(runtime_ls)

```
```{r}
####### Plotting Figure 5

library(latex2exp)
p01<-ggplot(mapping = aes(x=tab_recov_prob1[,2],y=(tab_recov_prob1[,1]),group =tab_recov_prob1[,3] ))+geom_point(aes(color = tab_recov_prob1[,3]) )+ geom_hline(yintercept = 1, color = "grey", linetype =2)  + geom_line(aes(color = tab_recov_prob1[,3]) )+labs(x=TeX("$Lp/d$"), y = "Empirical Coverage Probability",color = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) 

p<-ggplot(mapping = aes(x=tab_recov_prob[,2],y=(tab_recov_prob[,1]),group =tab_recov_prob[,3] ))+geom_point(aes(color = tab_recov_prob[,3]) )+ geom_hline(yintercept = 0.95, color = "grey", linetype =2)  + geom_line(aes(color = tab_recov_prob[,3]) )+labs(x=TeX("$Lp/d$"), y = "Empirical Coverage Probability",color = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) 
p1<-ggplot(mapping = aes(x=err_rate_tab[,2],y=(err_rate_tab[,1]),group =err_rate_tab[,3] ))+geom_point(aes(color = err_rate_tab[,3]) ) + geom_hline(yintercept = er_pca_500, color = "grey", linetype =2) +  geom_hline(yintercept = er_pca_1000, color = "grey", linetype =2)  +  geom_hline(yintercept = er_pca_2000, color = "grey", linetype =2)   + geom_line(aes(color = err_rate_tab[,3]) )+labs(x=TeX("$Lp/d$"), y = "Error Rate",color = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) 
p2<-ggplot(mapping = aes(x=runtime_tab[,2],y=(runtime_tab[,1]),group =runtime_tab[,3] ))+geom_point(aes(color = runtime_tab[,3]) )  + geom_line(aes(color = runtime_tab[,3]) )+labs(x=TeX("$Lp/d$"), y = "Running Time",color = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) 
```


Example 4: Missing Matrix 
```{r}
d= 500
K =3
set.seed(154)
u <- matrix(rnorm(d*K), d,K)
u <- svd(u)$u



vi_ls <- c()
runtime <- c()

qr <- qchisq(0.95, df=3)
tab_recov_prob_500 <- c()
err_rate_tab_500 <- c()
runtime_tab_500 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  L = round(rt*d/12)
  rec_tab <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("missing_mat_Results","results__500"), i, rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[17,] - H%*%u[17,]
    if(rt >= 1){
      Sig_hat1 <- solve(lmtild)%*%t(vtild)%*%(((Mtild[17,]^2*(1-that) + sig2hat    )/that)*vtild)%*%solve(lmtild)
    }else{
      Sig_hat1 <-  t(Bo)%*%t(Omega)%*%(((Mtild[17,]^2*(1-that) + sig2hat   )/that)*Omega)%*%Bo/L^2
    }
    cv <- t(dv)%*%solve(Sig_hat1)%*%dv <= qr
    
    
    
    rec_tab <- c(rec_tab,cv)
    
    err <- norm(vtild%*%t(vtild) - u%*%t(u),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_500<-rbind(err_rate_tab_500,c(mean(err_rate),rt, d))
  tab_recov_prob_500 <- rbind(tab_recov_prob_500,c(mean(rec_tab),rt, d))
  runtime_tab_500<-rbind(runtime_tab_500,c(mean(runtime_ls),rt, d))
}

###traditional PCA
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_4/pca/results/results__500", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - u%*%t(u),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_500 <- mean(err_rate)
runtime_pca_500 <- mean(runtime_ls)

d= 1000
K =3
set.seed(154)
u <- matrix(rnorm(d*K), d,K)
u <- svd(u)$u


vi_ls <- c()
runtime <- c()

qr <- qchisq(0.95, df=3)
tab_recov_prob_1000 <- c()
err_rate_tab_1000 <- c()
runtime_tab_1000 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  L = round(rt*d/12)
  rec_tab <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("missing_mat_Results","results__1000"), i, rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[17,] - H%*%u[17,]
    if(rt >= 1){
      Sig_hat1 <- solve(lmtild)%*%t(vtild)%*%(((Mtild[17,]^2*(1-that) + sig2hat    )/that)*vtild)%*%solve(lmtild)
    }else{
      Sig_hat1 <-  t(Bo)%*%t(Omega)%*%(((Mtild[17,]^2*(1-that) + sig2hat   )/that)*Omega)%*%Bo/L^2
    }
    cv <- t(dv)%*%solve(Sig_hat1)%*%dv <= qr
    
    
    
    rec_tab <- c(rec_tab,cv)
    
    err <- norm(vtild%*%t(vtild) - u%*%t(u),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_1000<-rbind(err_rate_tab_1000,c(mean(err_rate),rt, d))
  tab_recov_prob_1000 <- rbind(tab_recov_prob_1000,c(mean(rec_tab),rt, d))
  runtime_tab_1000<-rbind(runtime_tab_1000,c(mean(runtime_ls),rt, d))
}

###traditional PCA
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_4/pca/results/results__1000", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - u%*%t(u),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_1000 <- mean(err_rate)
runtime_pca_1000 <- mean(runtime_ls)

d= 2000
K =3
set.seed(154)
u <- matrix(rnorm(d*K), d,K)
u <- svd(u)$u


vi_ls <- c()
runtime <- c()

qr <- qchisq(0.95, df=3)
tab_recov_prob_2000 <- c()
err_rate_tab_2000 <- c()
runtime_tab_2000 <- c()
for (rt in c(0.2,0.6,0.9,1,1.2, 2,5,10)){
  L = round(rt*d/12)
  rec_tab <- c()
  err_rate <- c()
  runtime_ls <- c()
  for (i in 1:300){
    fname  <- paste(here("missing_mat_Results","results__2000"), i, rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    dv <- vtild[17,] - H%*%u[17,]
    if(rt >= 1){
      Sig_hat1 <- solve(lmtild)%*%t(vtild)%*%(((Mtild[17,]^2*(1-that) + sig2hat    )/that)*vtild)%*%solve(lmtild)
    }else{
      Sig_hat1 <-  t(Bo)%*%t(Omega)%*%(((Mtild[17,]^2*(1-that) + sig2hat   )/that)*Omega)%*%Bo/L^2
    }
    cv <-  t(dv)%*%solve(Sig_hat1)%*%dv <= qr
    
    
    
    rec_tab <- c(rec_tab,cv)
    
    err <- norm(vtild%*%t(vtild) - u%*%t(u),type = "F")
    err_rate<-c(err_rate,err)
    runtime_ls <- c(runtime_ls, runtime)
    
  }
  err_rate_tab_2000<-rbind(err_rate_tab_2000,c(mean(err_rate),rt, d))
  tab_recov_prob_2000 <- rbind(tab_recov_prob_2000,c(mean(rec_tab),rt, d))
  runtime_tab_2000<-rbind(runtime_tab_2000,c(mean(runtime_ls),rt, d))
}

###traditional PCA
err_rate <- c()
runtime_ls <- c()
for (i in 1:100){
  fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_4/pca/results/results__2000", i, ".RData",sep = "_")
  load(fname)
  
  
  err <- norm(vkh%*%t(vkh) - u%*%t(u),type = "F")
  err_rate<-c(err_rate,err)
  runtime_ls <- c(runtime_ls, runtime)
  
}
er_pca_2000 <- mean(err_rate)
runtime_pca_2000 <- mean(runtime_ls)


#### Tables of results for plotting Figure 6
err_rate_tab <- rbind(err_rate_tab_500,err_rate_tab_1000, err_rate_tab_2000)
err_rate_tab <- data.frame(err_rate_tab)
err_rate_tab$X3<- as.factor(err_rate_tab$X3 )


tab_recov_prob <- rbind(tab_recov_prob_500, tab_recov_prob_1000, tab_recov_prob_2000)

runtime_tab <- rbind(runtime_tab_500, runtime_tab_1000, runtime_tab_2000)
runtime_tab <- data.frame(runtime_tab)
runtime_tab$X3<- as.factor(runtime_tab$X3 )

tab_recov_prob <- data.frame(tab_recov_prob)
tab_recov_prob$X3<- as.factor(tab_recov_prob$X3 )

#### Plotting Figure 6
library(latex2exp)
p<-ggplot(mapping = aes(x=tab_recov_prob[,2],y=(tab_recov_prob[,1]),group =tab_recov_prob[,3] ))+geom_point(aes(color = tab_recov_prob[,3]) )+ geom_hline(yintercept = 0.95, color = "grey", linetype =2)  + geom_line(aes(color = tab_recov_prob[,3]) )+labs(x=TeX("$Lp/d$"), y = "Empirical Coverage Probability",color = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) 
p1<-ggplot(mapping = aes(x=err_rate_tab[,2],y=(err_rate_tab[,1]),group =err_rate_tab[,3] ))+geom_point(aes(color = err_rate_tab[,3]) ) + geom_hline(yintercept = er_pca_500, color = "grey", linetype =2) +  geom_hline(yintercept = er_pca_1000, color = "grey", linetype =2)  +  geom_hline(yintercept = er_pca_2000, color = "grey", linetype =2)   + geom_line(aes(color = err_rate_tab[,3]) )+labs(x=TeX("$Lp/d$"), y = "Error Rate",color = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) 
p2<-ggplot(mapping = aes(x=runtime_tab[,2],y=(runtime_tab[,1]),group =runtime_tab[,3] ))+geom_point(aes(color = runtime_tab[,3]) )  + geom_line(aes(color = runtime_tab[,3]) )+labs(x=TeX("$Lp/d$"), y = "Running Time",color = TeX("$d$"))+theme_bw()+theme(text=element_text(family="Times", size=12)) 
```
```{r}

####### QQ plots in Figure 6
d= 2000
K =3
set.seed(154)
u <- matrix(rnorm(d*K), d,K)
u <- svd(u)$u


vi_ls <- c()


for(rt in c(0.2,10)){
  for (i in 1:300){
    fname  <- paste("/ncf/xlin_covid/Users/sshen/dissertation_1.5/example_4_new/results/results__2000", i, rt, ".RData",sep = "_")
    load(fname)
    svdh <- svd(t(vtild)%*%u)
    H <- svdh$u %*% t(svdh$v)
    if(rt >= 1){
      Sig_hat1 <- solve(lmtild)%*%t(vtild)%*%(((Mtild[17,]^2*(1-that) + sig2hat    )/that)*vtild)%*%solve(lmtild)
    }else{
      Sig_hat1 <-  t(Bo)%*%t(Omega)%*%(((Mtild[17,]^2*(1-that) + sig2hat   )/that)*Omega)%*%Bo/L^2
    }
    
    svdsig <- svd(Sig_hat1)
    sig_sqrt <- svdsig$u %*% diag((svdsig$d)^{-0.5}) %*% t(svdsig$u)
    vi <- vtild[17,] - H%*% u[17,]
    vi_ls <- rbind(vi_ls,c(t(sig_sqrt%*%(vi)),rt))
    
    
  }
}

vi_ls <- data.frame(vi_ls)
vi_ls[4] <- factor(vi_ls[,4])
p1 <- ggplot()+geom_qq(aes(sample = vi_ls[,1],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme_bw()+theme(axis.text=element_text(family="Times", size=12),axis.title=element_text(family="Times", size=12),legend.text=element_text(family="Times", size=12))+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{v}_{1}$"), color = TeX("$Lp/d$"))
p2 <- ggplot()+geom_qq(aes(sample = vi_ls[,2],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(family="Times", size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{v}_{2}$"), color = TeX("$Lp/d$"))
p3 <- ggplot()+geom_qq(aes(sample = vi_ls[,3],group = vi_ls[,4], color = vi_ls[,4]),size=0.5)+theme(axis.text=element_text(family="Times", size=15),axis.title=element_text(size=16,face="bold"),legend.text=element_text(family="Times", size=12))+theme_bw()+labs(x = "Standard Normal Quantiles", y = TeX("Empirical Quantiles for $\\tilde{v}_{3}$"), color = TeX("$Lp/d$"))
```


